POST https://back-end-ylkyngweob.now.sh/api/products
Content-Type: application/json

{
  "name": "Muffin",
  "price": 7,
  "category": "food",
  "stockRemaining": 25
}

###

GET https://back-end-ylkyngweob.now.sh/api/products

###

PUT https://back-end-ylkyngweob.now.sh/api/products
Content-Type: application/json

{
  "name": "Fancy Coffee",
  "price": 10,
  "category": "drink",
  "stockRemaining": 100
}

###

DELETE https://back-end-ylkyngweob.now.sh/api/products/59533179f38e9191629d6e5b

###

GET  https://back-end-ylkyngweob.now.sh/api/products/59533498ca307c9286